// UI strings for the six supported languages (en/tr/pl/de/fr/it). A direct port of the
// Android `values[-xx]/strings.xml` sets. Lookup falls back to English for any missing key.
// (Korean was removed in #v22 — its font never read right; see future-plans/korean-language.md.)

const Map<String, Map<String, String>> _s = {
  'en': {
    'work': 'FOCUS', 'break': 'BREAK', 'start': 'START', 'pause': 'PAUSE', 'reset': 'RESET',
    'autoBreak': 'AUTO-START', 'startBreakTitle': 'Start the break?', 'startSessionTitle': 'Start the next session?',
    'logHistory': 'LOG HISTORY', 'changeLabel': 'CHANGE LABEL', 'noLogs': 'No sessions yet', 'pageOf': 'PAGE {0}/{1}',
    'switchMode': '>> SWITCH MODE', 'session': 'SESSION {0} / {1}', 'allDone': 'ALL DONE!',
    'workDone': 'FOCUS DONE!', 'breakDone': 'BREAK OVER!',
    'settings': 'SETTINGS', 'theme': 'THEME', 'save': 'SAVE', 'close': 'CLOSE',
    'timerMode': 'TIMER MODE', 'stopwatch': 'STOPWATCH', 'pomodoro': 'POMODORO',
    'study': 'STUDY (MIN)', 'breakMin': 'BREAK (MIN)', 'sessions': 'SESSIONS',
    'settingsSaved': 'SETTINGS SAVED', 'language': 'LANGUAGE',
    'label': 'LABEL', 'newLabel': 'NEW LABEL', 'add': 'ADD', 'pickColor': 'PICK A COLOR',
    'renameTitle': 'RENAME LABEL', 'renameHint': 'Long-press a label to rename it.',
    'removeTitle': 'Remove label?', 'removeMsg': 'Remove the label "{0}"?', 'yes': 'YES', 'no': 'NO',
    'stats': 'STATS', 'today': 'TODAY', 'week': 'THIS WEEK', 'month': 'THIS MONTH',
    'year': 'THIS YEAR', 'all': 'ALL TIME', 'byLabelMonth': 'BY LABEL · {0}',
    'chartBar': 'BAR', 'chartLine': 'TREND', 'chartPie': 'PIE', 'chartNoData': 'No focus minutes this month.',
    'statCurrent': 'CURRENT', 'statAverage': 'AVERAGE', 'statBest': 'BEST',
    'pDaily': 'DAILY', 'pWeekly': 'WEEKLY', 'pMonthly': 'MONTHLY', 'pYearly': 'YEARLY', 'pAll': 'ALL', 'byLabel': 'BY LABEL',
    'p18Weeks': '18 WEEKS',
    'shop': 'SHOP', 'buy': 'BUY', 'owned': 'OWNED {0}', 'notEnough': 'NOT ENOUGH COINS',
    'purchased': 'PURCHASED', 'shopHelp': '1 coin / 5 focus min · flowers 10 · roads & fences 5',
    'shopObjects': 'DECOR',
    'catFlowers': 'FLOWERS', 'catOuter': 'OUTER DECOR', 'catInner': 'INNER DECOR', 'catPets': 'PETS', 'comingSoon': 'COMING SOON',
    'road_concrete': 'CONCRETE', 'road_wood': 'WOOD PATH', 'road_dirt': 'DIRT PATH', 'road_stone': 'STONE PATH',
    'fence_wood': 'WOOD FENCE', 'fence_dark': 'DARK FENCE', 'fence_stone': 'STONE FENCE',
    'garden': 'GARDEN', 'gardenHelp': 'CUSTOMIZE, then tap tiles. Pinch zoom · drag pan · twist to rotate.',
    'customize': 'CUSTOMIZE', 'done': 'DONE', 'upgrade': 'EXPAND ({0})', 'maxSize': 'MAX SIZE',
    'gardenSize': '{0} × {1}', 'upgraded': 'GARDEN EXPANDED', 'pickFlower': 'PLACE WHAT?',
    'clearTile': 'CLEAR TILE', 'needFlowers': 'Buy something in the SHOP first.',
    'noneLeft': 'None of that left to place.', 'recenter': 'RECENTER',
    'peek': 'HIDE UI', 'camera': 'CAMERA', 'capture': 'CAPTURE', 'share': 'SAVE / SHARE',
    'setBackdrop': 'SET AS BACKDROP', 'clearBackdrop': 'CLEAR BACKDROP', 'cancel': 'CANCEL',
    'setLiveWallpaper': 'SET AS LIVE WALLPAPER', 'wallpaperSet': 'WALLPAPER SET',
    'wallpaperFailed': "Couldn't open the wallpaper picker.",
    'homeMode': 'HOME SCREEN', 'clean': 'CLEAN', 'gardenMode': 'GARDEN',
    'appBlocker': 'APP BLOCKER', 'blockedApps': 'BLOCKED APPS',
    'blockerPermTitle': 'PERMISSIONS NEEDED',
    'blockerPermBody': 'Pixel Pomo needs Accessibility (to see which app is open) and Draw-over-apps (to show the focus screen).',
    'grantAccess': 'GRANT ACCESSIBILITY', 'grantOverlay': 'GRANT OVERLAY',
    'stayFocused': 'STAY FOCUSED', 'backToPomo': 'BACK TO PIXEL POMO',
    'pickBlocked': 'TAP APPS TO BLOCK DURING FOCUS',
    'habits': 'HABITS', 'money': 'MONEY TRACKER', 'mood': 'HOW WAS TODAY?',
    'addHabit': 'ADD HABIT', 'habitName': 'HABIT NAME', 'daysTimes': '{0} DAYS · {1} TIMES',
    'daysTimesTotal': '{0} DAYS · {1} TIMES · {2}',
    'style': 'STYLE', 'styleHorizontal': 'HORIZONTAL', 'styleVertical': 'VERTICAL',
    'streakN': '{0} DAY STREAK', 'noHabits': 'Add a habit or start a focus session.',
    'labelHabit': 'FOCUS LABEL', 'removeHabitMsg': 'Remove the habit "{0}"?',
    'income': 'INCOME', 'expense': 'EXPENSE', 'addExpense': '+ EXPENSE', 'addIncome': '+ INCOME',
    'amount': 'AMOUNT', 'category': 'CATEGORY', 'note': 'NOTE (OPTIONAL)', 'currency': 'CURRENCY',
    'moneySettings': 'MONEY SETTINGS', 'mainCurrency': 'MAIN CURRENCY', 'dailyRate': 'DAILY BUDGET',
    'dailyRateHelp': 'Spend under this in a day → +1 coin. 0 = off.', 'noTx': 'No entries this month.',
    'spentToday': 'SPENT TODAY', 'ratesUpdated': 'RATES UPDATED', 'offline': 'OFFLINE · CACHED RATES',
    'catFood': 'FOOD', 'catTransport': 'TRANSPORT', 'catHome': 'HOME', 'catFun': 'FUN',
    'catHealth': 'HEALTH', 'catShopping': 'SHOPPING', 'catEducation': 'EDUCATION', 'catOther': 'OTHER',
    'catSalary': 'SALARY', 'catGift': 'GIFT',
    'net': 'NET', 'addCategory': 'ADD CATEGORY', 'categoryNameHint': 'CATEGORY NAME',
    'removeCategoryMsg': 'Remove the category "{0}"?', 'noRates': 'Rates not loaded — amounts shown unconverted.',
    'noMoneyData': 'No entries in this window.', 'noSessionsPeriod': 'No focus sessions here yet.',
    'weekdayShort': 'MO,TU,WE,TH,FR,SA,SU',
    'yearInPixels': 'YOUR YEAR IN PIXELS (ALL DATA)', 'moodTracker': 'MOOD TRACKER', 'goals': 'YOUR GOALS', 'focusSessions': 'FOCUS SESSIONS',
    'sessionsTimelineWeek': 'SESSION TIMELINE IN A WEEK', 'sessionHeatmap': 'SESSION HEATMAP',
    'sessionsInPixels': 'SESSIONS IN PIXELS',
  },
  'tr': {
    'work': 'ODAK', 'break': 'MOLA', 'start': 'BAŞLAT', 'pause': 'DURAKLAT', 'reset': 'SIFIRLA',
    'autoBreak': 'OTOMATİK BAŞLAT', 'startBreakTitle': 'Molayı başlat?', 'startSessionTitle': 'Sonraki seans başlasın mı?',
    'logHistory': 'KAYIT GEÇMİŞİ', 'changeLabel': 'ETİKETİ DEĞİŞTİR', 'noLogs': 'Henüz seans yok', 'pageOf': 'SAYFA {0}/{1}',
    'switchMode': '>> MOD DEĞİŞTİR', 'session': 'SEANS {0} / {1}', 'allDone': 'BİTTİ!',
    'workDone': 'ODAK BİTTİ!', 'breakDone': 'MOLA BİTTİ!',
    'settings': 'AYARLAR', 'theme': 'TEMA', 'save': 'KAYDET', 'close': 'KAPAT',
    'timerMode': 'ZAMANLAYICI MODU', 'stopwatch': 'KRONOMETRE', 'pomodoro': 'POMODORO',
    'study': 'ÇALIŞMA (DK)', 'breakMin': 'MOLA (DK)', 'sessions': 'SEANS',
    'settingsSaved': 'AYARLAR KAYDEDİLDİ', 'language': 'DİL',
    'label': 'ETİKET', 'newLabel': 'YENİ ETİKET', 'add': 'EKLE', 'pickColor': 'RENK SEÇ',
    'renameTitle': 'ETİKETİ DEĞİŞTİR', 'renameHint': 'Yeniden adlandırmak için basılı tut.',
    'removeTitle': 'Etiket silinsin mi?', 'removeMsg': '"{0}" etiketi silinsin mi?', 'yes': 'EVET', 'no': 'HAYIR',
    'stats': 'İSTATİSTİK', 'today': 'BUGÜN', 'week': 'BU HAFTA', 'month': 'BU AY',
    'year': 'BU YIL', 'all': 'TÜM ZAMANLAR', 'byLabelMonth': 'ETİKETE GÖRE · {0}',
    'chartBar': 'ÇUBUK', 'chartLine': 'TREND', 'chartPie': 'PASTA', 'chartNoData': 'Bu ay odak dakikası yok.',
    'statCurrent': 'MEVCUT', 'statAverage': 'ORTALAMA', 'statBest': 'EN İYİ',
    'pDaily': 'GÜNLÜK', 'pWeekly': 'HAFTALIK', 'pMonthly': 'AYLIK', 'pYearly': 'YILLIK', 'pAll': 'TÜMÜ', 'byLabel': 'ETİKETE GÖRE',
    'p18Weeks': '18 HAFTA',
    'shop': 'MAĞAZA', 'buy': 'AL', 'owned': 'SAHİP {0}', 'notEnough': 'YETERLİ ALTIN YOK',
    'purchased': 'SATIN ALINDI', 'shopHelp': '5 odak dk = 1 altın · çiçek 10 · yol ve çit 5',
    'shopObjects': 'SÜS',
    'catFlowers': 'ÇİÇEKLER', 'catOuter': 'DIŞ SÜS', 'catInner': 'İÇ SÜS', 'catPets': 'EVCİLLER', 'comingSoon': 'YAKINDA',
    'road_concrete': 'BETON', 'road_wood': 'TAHTA YOL', 'road_dirt': 'TOPRAK YOL', 'road_stone': 'TAŞ YOL',
    'fence_wood': 'TAHTA ÇİT', 'fence_dark': 'KOYU ÇİT', 'fence_stone': 'TAŞ ÇİT',
    'garden': 'BAHÇE', 'gardenHelp': 'ÖZELLEŞTİR, sonra dokun. Yakınlaştır · sürükle · çevir.',
    'customize': 'ÖZELLEŞTİR', 'done': 'TAMAM', 'upgrade': 'BÜYÜT ({0})', 'maxSize': 'MAKS BOYUT',
    'gardenSize': '{0} × {1}', 'upgraded': 'BAHÇE BÜYÜTÜLDÜ', 'pickFlower': 'NE KOYALIM?',
    'clearTile': 'KAREYİ TEMİZLE', 'needFlowers': 'Önce MAĞAZA\'dan bir şey al.',
    'noneLeft': 'Koyacak o şeyden kalmadı.', 'recenter': 'ORTALA',
    'peek': 'GİZLE', 'camera': 'KAMERA', 'capture': 'ÇEK', 'share': 'KAYDET / PAYLAŞ',
    'setBackdrop': 'ARKA PLAN YAP', 'clearBackdrop': 'ARKA PLANI SİL', 'cancel': 'İPTAL',
    'setLiveWallpaper': 'CANLI DUVAR KAĞIDI YAP', 'wallpaperSet': 'DUVAR KAĞIDI AYARLANDI',
    'wallpaperFailed': 'Duvar kağıdı seçici açılamadı.',
    'homeMode': 'ANA EKRAN', 'clean': 'SADE', 'gardenMode': 'BAHÇE',
    'appBlocker': 'UYGULAMA ENGELLEYİCİ', 'blockedApps': 'ENGELLİ UYGULAMALAR',
    'blockerPermTitle': 'İZİN GEREKLİ',
    'blockerPermBody': 'Pixel Pomo, hangi uygulamanın açık olduğunu görmek için Erişilebilirlik ve odak ekranını göstermek için Üstte-göster iznine ihtiyaç duyar.',
    'grantAccess': 'ERİŞİLEBİLİRLİK VER', 'grantOverlay': 'ÜSTTE GÖSTER VER',
    'stayFocused': 'ODAKTA KAL', 'backToPomo': "PIXEL POMO'YA DÖN",
    'pickBlocked': 'ODAKTA ENGELLENECEK UYGULAMALARA DOKUN',
    'habits': 'ALIŞKANLIKLAR', 'money': 'PARA TAKİBİ', 'mood': 'BUGÜN NASILDI?',
    'addHabit': 'ALIŞKANLIK EKLE', 'habitName': 'ALIŞKANLIK ADI', 'daysTimes': '{0} GÜN · {1} KEZ',
    'daysTimesTotal': '{0} GÜN · {1} KEZ · {2}',
    'style': 'STİL', 'styleHorizontal': 'YATAY', 'styleVertical': 'DİKEY',
    'streakN': '{0} GÜN SERİ', 'noHabits': 'Bir alışkanlık ekle veya odak seansı başlat.',
    'labelHabit': 'ODAK ETİKETİ', 'removeHabitMsg': '"{0}" alışkanlığı silinsin mi?',
    'income': 'GELİR', 'expense': 'GİDER', 'addExpense': '+ GİDER', 'addIncome': '+ GELİR',
    'amount': 'TUTAR', 'category': 'KATEGORİ', 'note': 'NOT (İSTEĞE BAĞLI)', 'currency': 'PARA BİRİMİ',
    'moneySettings': 'PARA AYARLARI', 'mainCurrency': 'ANA PARA BİRİMİ', 'dailyRate': 'GÜNLÜK BÜTÇE',
    'dailyRateHelp': 'Günde bunun altında harca → +1 altın. 0 = kapalı.', 'noTx': 'Bu ay kayıt yok.',
    'spentToday': 'BUGÜN HARCANAN', 'ratesUpdated': 'KURLAR GÜNCELLENDİ', 'offline': 'ÇEVRİMDIŞI · ÖNBELLEK',
    'catFood': 'YEMEK', 'catTransport': 'ULAŞIM', 'catHome': 'EV', 'catFun': 'EĞLENCE',
    'catHealth': 'SAĞLIK', 'catShopping': 'ALIŞVERİŞ', 'catEducation': 'EĞİTİM', 'catOther': 'DİĞER',
    'catSalary': 'MAAŞ', 'catGift': 'HEDİYE',
    'net': 'NET', 'addCategory': 'KATEGORİ EKLE', 'categoryNameHint': 'KATEGORİ ADI',
    'removeCategoryMsg': '"{0}" kategorisi silinsin mi?', 'noRates': 'Kurlar yüklenmedi — tutarlar çevrilmedi.',
    'noMoneyData': 'Bu aralıkta kayıt yok.', 'noSessionsPeriod': 'Burada henüz hiç odak seansı yok.',
    'weekdayShort': 'PT,SA,ÇA,PE,CU,CT,PZ',
    'yearInPixels': 'PİKSELLERDE YILIN (TÜM VERİ)', 'moodTracker': 'RUH HALİ TAKİBİ', 'goals': 'HEDEFLERİN', 'focusSessions': 'ODAK SEANSLARI',
    'sessionsTimelineWeek': 'HAFTALIK SEANS ÇİZELGESİ', 'sessionHeatmap': 'SEANS ISI HARİTASI',
    'sessionsInPixels': 'PİKSELLERDE SEANSLAR',
  },
  'pl': {
    'work': 'SKUPIENIE', 'break': 'PRZERWA', 'start': 'START', 'pause': 'PAUZA', 'reset': 'RESET',
    'autoBreak': 'AUTO-START', 'startBreakTitle': 'Zacząć przerwę?', 'startSessionTitle': 'Zacząć następną sesję?',
    'logHistory': 'HISTORIA', 'changeLabel': 'ZMIEŃ ETYKIETĘ', 'noLogs': 'Brak sesji', 'pageOf': 'STRONA {0}/{1}',
    'switchMode': '>> ZMIEŃ TRYB', 'session': 'SESJA {0} / {1}', 'allDone': 'GOTOWE!',
    'workDone': 'KONIEC SKUPIENIA!', 'breakDone': 'KONIEC PRZERWY!',
    'settings': 'USTAWIENIA', 'theme': 'MOTYW', 'save': 'ZAPISZ', 'close': 'ZAMKNIJ',
    'timerMode': 'TRYB ZEGARA', 'stopwatch': 'STOPER', 'pomodoro': 'POMODORO',
    'study': 'PRACA (MIN)', 'breakMin': 'PRZERWA (MIN)', 'sessions': 'SESJE',
    'settingsSaved': 'ZAPISANO', 'language': 'JĘZYK',
    'label': 'ETYKIETA', 'newLabel': 'NOWA ETYKIETA', 'add': 'DODAJ', 'pickColor': 'WYBIERZ KOLOR',
    'renameTitle': 'ZMIEŃ NAZWĘ', 'renameHint': 'Przytrzymaj, aby zmienić nazwę.',
    'removeTitle': 'Usunąć etykietę?', 'removeMsg': 'Usunąć etykietę "{0}"?', 'yes': 'TAK', 'no': 'NIE',
    'stats': 'STATYSTYKI', 'today': 'DZIŚ', 'week': 'TEN TYDZIEŃ', 'month': 'TEN MIESIĄC',
    'year': 'TEN ROK', 'all': 'CAŁY CZAS', 'byLabelMonth': 'WG ETYKIETY · {0}',
    'chartBar': 'SŁUPKI', 'chartLine': 'TREND', 'chartPie': 'KOŁO', 'chartNoData': 'Brak minut w tym miesiącu.',
    'statCurrent': 'OBECNY', 'statAverage': 'ŚREDNIA', 'statBest': 'NAJLEPSZY',
    'pDaily': 'DZIENNE', 'pWeekly': 'TYGODNIE', 'pMonthly': 'MIESIĄC', 'pYearly': 'ROCZNE', 'pAll': 'WSZYSTKO', 'byLabel': 'WG ETYKIETY',
    'p18Weeks': '18 TYGODNI',
    'shop': 'SKLEP', 'buy': 'KUP', 'owned': 'MASZ {0}', 'notEnough': 'ZA MAŁO MONET',
    'purchased': 'KUPIONO', 'shopHelp': '1 moneta / 5 min · kwiat 10 · droga i płot 5',
    'shopObjects': 'DEKORACJE',
    'catFlowers': 'KWIATY', 'catOuter': 'DEKOR ZEWN.', 'catInner': 'DEKOR WEWN.', 'catPets': 'ZWIERZAKI', 'comingSoon': 'WKRÓTCE',
    'road_concrete': 'BETON', 'road_wood': 'DROGA DREW.', 'road_dirt': 'DROGA ZIEM.', 'road_stone': 'DROGA KAM.',
    'fence_wood': 'PŁOT DREW.', 'fence_dark': 'CIEMNY PŁOT', 'fence_stone': 'PŁOT KAM.',
    'garden': 'OGRÓD', 'gardenHelp': 'DOSTOSUJ, potem dotykaj. Szczyp · przeciągnij · obróć.',
    'customize': 'DOSTOSUJ', 'done': 'GOTOWE', 'upgrade': 'ROZBUDUJ ({0})', 'maxSize': 'MAKS. ROZMIAR',
    'gardenSize': '{0} × {1}', 'upgraded': 'OGRÓD ROZBUDOWANY', 'pickFlower': 'CO POSTAWIĆ?',
    'clearTile': 'WYCZYŚĆ POLE', 'needFlowers': 'Najpierw kup coś w SKLEPIE.',
    'noneLeft': 'Nie masz już tego.', 'recenter': 'WYŚRODKUJ',
    'peek': 'UKRYJ UI', 'camera': 'APARAT', 'capture': 'ZRÓB', 'share': 'ZAPISZ / UDOSTĘPNIJ',
    'setBackdrop': 'USTAW TŁO', 'clearBackdrop': 'USUŃ TŁO', 'cancel': 'ANULUJ',
    'setLiveWallpaper': 'USTAW TAPETĘ', 'wallpaperSet': 'USTAWIONO TAPETĘ',
    'wallpaperFailed': 'Nie można otworzyć wyboru tapety.',
    'homeMode': 'EKRAN GŁÓWNY', 'clean': 'CZYSTY', 'gardenMode': 'OGRÓD',
    'appBlocker': 'BLOKADA APEK', 'blockedApps': 'ZABLOKOWANE APKI',
    'blockerPermTitle': 'POTRZEBNE UPRAWNIENIA',
    'blockerPermBody': 'Pixel Pomo potrzebuje Dostępności (by widzieć otwartą apkę) i Nakładki (by pokazać ekran skupienia).',
    'grantAccess': 'WŁĄCZ DOSTĘPNOŚĆ', 'grantOverlay': 'WŁĄCZ NAKŁADKĘ',
    'stayFocused': 'SKUP SIĘ', 'backToPomo': 'WRÓĆ DO PIXEL POMO',
    'pickBlocked': 'DOTKNIJ APKI DO ZABLOKOWANIA',
    'habits': 'NAWYKI', 'money': 'ŚLEDZENIE FINANSÓW', 'mood': 'JAK MINĄŁ DZIEŃ?',
    'addHabit': 'DODAJ NAWYK', 'habitName': 'NAZWA NAWYKU', 'daysTimes': '{0} DNI · {1} RAZY',
    'daysTimesTotal': '{0} DNI · {1} RAZY · {2}',
    'style': 'STYL', 'styleHorizontal': 'POZIOMY', 'styleVertical': 'PIONOWY',
    'streakN': 'SERIA {0} DNI', 'noHabits': 'Dodaj nawyk lub zacznij sesję skupienia.',
    'labelHabit': 'ETYKIETA SKUPIENIA', 'removeHabitMsg': 'Usunąć nawyk „{0}"?',
    'income': 'PRZYCHÓD', 'expense': 'WYDATEK', 'addExpense': '+ WYDATEK', 'addIncome': '+ PRZYCHÓD',
    'amount': 'KWOTA', 'category': 'KATEGORIA', 'note': 'NOTATKA (OPCJA)', 'currency': 'WALUTA',
    'moneySettings': 'USTAWIENIA PIENIĘDZY', 'mainCurrency': 'GŁÓWNA WALUTA', 'dailyRate': 'DZIENNY BUDŻET',
    'dailyRateHelp': 'Wydaj mniej dziennie → +1 moneta. 0 = wył.', 'noTx': 'Brak wpisów w tym miesiącu.',
    'spentToday': 'WYDANE DZIŚ', 'ratesUpdated': 'KURSY ZAKTUALIZOWANE', 'offline': 'OFFLINE · Z PAMIĘCI',
    'catFood': 'JEDZENIE', 'catTransport': 'TRANSPORT', 'catHome': 'DOM', 'catFun': 'ROZRYWKA',
    'catHealth': 'ZDROWIE', 'catShopping': 'ZAKUPY', 'catEducation': 'EDUKACJA', 'catOther': 'INNE',
    'catSalary': 'PENSJA', 'catGift': 'PREZENT',
    'net': 'NETTO', 'addCategory': 'DODAJ KATEGORIĘ', 'categoryNameHint': 'NAZWA KATEGORII',
    'removeCategoryMsg': 'Usunąć kategorię "{0}"?', 'noRates': 'Brak kursów — kwoty bez przeliczenia.',
    'noMoneyData': 'Brak wpisów w tym okresie.', 'noSessionsPeriod': 'Brak sesji skupienia w tym okresie.',
    'weekdayShort': 'PN,WT,ŚR,CZ,PT,SO,ND',
    'yearInPixels': 'TWÓJ ROK W PIKSELACH (WSZYSTKO)', 'moodTracker': 'ŚLEDZENIE NASTROJU', 'goals': 'TWOJE CELE', 'focusSessions': 'SESJE SKUPIENIA',
    'sessionsTimelineWeek': 'OŚ SESJI W TYGODNIU', 'sessionHeatmap': 'MAPA CIEPŁA SESJI',
    'sessionsInPixels': 'SESJE W PIKSELACH',
  },
  'de': {
    'work': 'FOKUS', 'break': 'PAUSE', 'start': 'START', 'pause': 'PAUSE', 'reset': 'ZURÜCK',
    'autoBreak': 'AUTO-START', 'startBreakTitle': 'Pause starten?', 'startSessionTitle': 'Nächste Sitzung starten?',
    'logHistory': 'VERLAUF', 'changeLabel': 'LABEL ÄNDERN', 'noLogs': 'Noch keine Sitzungen', 'pageOf': 'SEITE {0}/{1}',
    'switchMode': '>> MODUS WECHSELN', 'session': 'RUNDE {0} / {1}', 'allDone': 'FERTIG!',
    'workDone': 'FOKUS FERTIG!', 'breakDone': 'PAUSE VORBEI!',
    'settings': 'EINSTELLUNGEN', 'theme': 'THEMA', 'save': 'SPEICHERN', 'close': 'SCHLIESSEN',
    'timerMode': 'TIMER-MODUS', 'stopwatch': 'STOPPUHR', 'pomodoro': 'POMODORO',
    'study': 'ARBEIT (MIN)', 'breakMin': 'PAUSE (MIN)', 'sessions': 'RUNDEN',
    'settingsSaved': 'GESPEICHERT', 'language': 'SPRACHE',
    'label': 'LABEL', 'newLabel': 'NEUES LABEL', 'add': 'HINZU', 'pickColor': 'FARBE WÄHLEN',
    'renameTitle': 'LABEL UMBENENNEN', 'renameHint': 'Zum Umbenennen lange drücken.',
    'removeTitle': 'Label löschen?', 'removeMsg': 'Label "{0}" löschen?', 'yes': 'JA', 'no': 'NEIN',
    'stats': 'STATISTIK', 'today': 'HEUTE', 'week': 'DIESE WOCHE', 'month': 'DIESER MONAT',
    'year': 'DIESES JAHR', 'all': 'GESAMT', 'byLabelMonth': 'NACH LABEL · {0}',
    'chartBar': 'BALKEN', 'chartLine': 'TREND', 'chartPie': 'KREIS', 'chartNoData': 'Keine Minuten in diesem Monat.',
    'statCurrent': 'AKTUELL', 'statAverage': 'DURCHSCHN', 'statBest': 'BESTE',
    'pDaily': 'TÄGLICH', 'pWeekly': 'WÖCHENTL', 'pMonthly': 'MONATL', 'pYearly': 'JÄHRL', 'pAll': 'GESAMT', 'byLabel': 'NACH LABEL',
    'p18Weeks': '18 WOCHEN',
    'shop': 'SHOP', 'buy': 'KAUFEN', 'owned': 'BESITZ {0}', 'notEnough': 'ZU WENIG MÜNZEN',
    'purchased': 'GEKAUFT', 'shopHelp': '1 Münze / 5 Min · Blume 10 · Straße & Zaun 5',
    'shopObjects': 'DEKO',
    'catFlowers': 'BLUMEN', 'catOuter': 'AUSSEN-DEKO', 'catInner': 'INNEN-DEKO', 'catPets': 'TIERE', 'comingSoon': 'BALD',
    'road_concrete': 'BETON', 'road_wood': 'HOLZWEG', 'road_dirt': 'ERDWEG', 'road_stone': 'STEINWEG',
    'fence_wood': 'HOLZZAUN', 'fence_dark': 'DUNKLER ZAUN', 'fence_stone': 'STEINZAUN',
    'garden': 'GARTEN', 'gardenHelp': 'ANPASSEN, dann tippen. Zoomen · ziehen · drehen.',
    'customize': 'ANPASSEN', 'done': 'FERTIG', 'upgrade': 'ERWEITERN ({0})', 'maxSize': 'MAX. GRÖSSE',
    'gardenSize': '{0} × {1}', 'upgraded': 'GARTEN ERWEITERT', 'pickFlower': 'WAS SETZEN?',
    'clearTile': 'FELD LEEREN', 'needFlowers': 'Kaufe zuerst etwas im SHOP.',
    'noneLeft': 'Nichts davon mehr übrig.', 'recenter': 'ZENTRIEREN',
    'peek': 'UI AUS', 'camera': 'KAMERA', 'capture': 'AUFNAHME', 'share': 'SPEICHERN / TEILEN',
    'setBackdrop': 'ALS HINTERGRUND', 'clearBackdrop': 'HINTERGRUND LÖSCHEN', 'cancel': 'ABBRECHEN',
    'setLiveWallpaper': 'ALS LIVE-HINTERGRUND', 'wallpaperSet': 'HINTERGRUND GESETZT',
    'wallpaperFailed': 'Hintergrund-Auswahl ließ sich nicht öffnen.',
    'homeMode': 'STARTBILDSCHIRM', 'clean': 'SCHLICHT', 'gardenMode': 'GARTEN',
    'appBlocker': 'APP-BLOCKER', 'blockedApps': 'BLOCKIERTE APPS',
    'blockerPermTitle': 'BERECHTIGUNGEN NÖTIG',
    'blockerPermBody': 'Pixel Pomo braucht Bedienungshilfen (welche App offen ist) und Über-Apps-zeichnen (für den Fokus-Bildschirm).',
    'grantAccess': 'BEDIENUNGSHILFEN', 'grantOverlay': 'ÜBER-APPS ERLAUBEN',
    'stayFocused': 'BLEIB FOKUSSIERT', 'backToPomo': 'ZURÜCK ZU PIXEL POMO',
    'pickBlocked': 'APPS ZUM BLOCKIEREN ANTIPPEN',
    'habits': 'GEWOHNHEITEN', 'money': 'GELD-TRACKER', 'mood': 'WIE WAR HEUTE?',
    'addHabit': 'GEWOHNHEIT HINZUFÜGEN', 'habitName': 'NAME', 'daysTimes': '{0} TAGE · {1} MAL',
    'daysTimesTotal': '{0} TAGE · {1} MAL · {2}',
    'style': 'STIL', 'styleHorizontal': 'HORIZONTAL', 'styleVertical': 'VERTIKAL',
    'streakN': '{0} TAGE SERIE', 'noHabits': 'Gewohnheit hinzufügen oder Fokus starten.',
    'labelHabit': 'FOKUS-LABEL', 'removeHabitMsg': 'Gewohnheit „{0}" entfernen?',
    'income': 'EINNAHME', 'expense': 'AUSGABE', 'addExpense': '+ AUSGABE', 'addIncome': '+ EINNAHME',
    'amount': 'BETRAG', 'category': 'KATEGORIE', 'note': 'NOTIZ (OPTIONAL)', 'currency': 'WÄHRUNG',
    'moneySettings': 'GELD-EINSTELLUNGEN', 'mainCurrency': 'HAUPTWÄHRUNG', 'dailyRate': 'TAGESBUDGET',
    'dailyRateHelp': 'Weniger pro Tag → +1 Münze. 0 = aus.', 'noTx': 'Keine Einträge diesen Monat.',
    'spentToday': 'HEUTE AUSGEGEBEN', 'ratesUpdated': 'KURSE AKTUALISIERT', 'offline': 'OFFLINE · CACHE',
    'catFood': 'ESSEN', 'catTransport': 'TRANSPORT', 'catHome': 'ZUHAUSE', 'catFun': 'SPASS',
    'catHealth': 'GESUNDHEIT', 'catShopping': 'EINKAUF', 'catEducation': 'BILDUNG', 'catOther': 'SONSTIGES',
    'catSalary': 'GEHALT', 'catGift': 'GESCHENK',
    'net': 'NETTO', 'addCategory': 'KATEGORIE HINZUFÜGEN', 'categoryNameHint': 'KATEGORIENAME',
    'removeCategoryMsg': 'Kategorie "{0}" entfernen?', 'noRates': 'Keine Kurse — Beträge unkonvertiert.',
    'noMoneyData': 'Keine Einträge in diesem Zeitraum.', 'noSessionsPeriod': 'Noch keine Fokus-Sitzungen hier.',
    'weekdayShort': 'MO,DI,MI,DO,FR,SA,SO',
    'yearInPixels': 'DEIN JAHR IN PIXELN (ALLE DATEN)', 'moodTracker': 'STIMMUNGS-TRACKER', 'goals': 'DEINE ZIELE', 'focusSessions': 'FOKUS-SITZUNGEN',
    'sessionsTimelineWeek': 'SITZUNGSVERLAUF DER WOCHE', 'sessionHeatmap': 'SITZUNGS-HEATMAP',
    'sessionsInPixels': 'SITZUNGEN IN PIXELN',
  },
  'fr': {
    'work': 'FOCUS', 'break': 'PAUSE', 'start': 'DÉMARRER', 'pause': 'PAUSE', 'reset': 'RÉINIT.',
    'autoBreak': 'DÉMARRAGE AUTO', 'startBreakTitle': 'Commencer la pause ?', 'startSessionTitle': 'Démarrer la prochaine session ?',
    'logHistory': 'HISTORIQUE', 'changeLabel': "CHANGER L'ÉTIQUETTE", 'noLogs': 'Aucune session', 'pageOf': 'PAGE {0}/{1}',
    'switchMode': '>> CHANGER MODE', 'session': 'SESSION {0} / {1}', 'allDone': 'TERMINÉ !',
    'workDone': 'FOCUS TERMINÉ !', 'breakDone': 'PAUSE FINIE !',
    'settings': 'RÉGLAGES', 'theme': 'THÈME', 'save': 'ENREGISTRER', 'close': 'FERMER',
    'timerMode': 'MODE MINUTEUR', 'stopwatch': 'CHRONOMÈTRE', 'pomodoro': 'POMODORO',
    'study': 'TRAVAIL (MIN)', 'breakMin': 'PAUSE (MIN)', 'sessions': 'SESSIONS',
    'settingsSaved': 'RÉGLAGES ENREGISTRÉS', 'language': 'LANGUE',
    'label': 'ÉTIQUETTE', 'newLabel': 'NOUVELLE ÉTIQUETTE', 'add': 'AJOUTER', 'pickColor': 'CHOISIR COULEUR',
    'renameTitle': 'RENOMMER', 'renameHint': 'Appui long pour renommer.',
    'removeTitle': "Supprimer l'étiquette ?", 'removeMsg': 'Supprimer l\'étiquette "{0}" ?', 'yes': 'OUI', 'no': 'NON',
    'stats': 'STATS', 'today': "AUJOURD'HUI", 'week': 'CETTE SEMAINE', 'month': 'CE MOIS',
    'year': 'CETTE ANNÉE', 'all': 'TOUT', 'byLabelMonth': 'PAR ÉTIQUETTE · {0}',
    'chartBar': 'BARRES', 'chartLine': 'TENDANCE', 'chartPie': 'CAMEMBERT', 'chartNoData': 'Aucune minute ce mois-ci.',
    'statCurrent': 'ACTUEL', 'statAverage': 'MOYENNE', 'statBest': 'MEILLEUR',
    'pDaily': 'JOUR', 'pWeekly': 'SEMAINE', 'pMonthly': 'MOIS', 'pYearly': 'ANNÉE', 'pAll': 'TOUT', 'byLabel': 'PAR ÉTIQUETTE',
    'p18Weeks': '18 SEMAINES',
    'shop': 'BOUTIQUE', 'buy': 'ACHETER', 'owned': 'POSSÉDÉ {0}', 'notEnough': 'PAS ASSEZ DE PIÈCES',
    'purchased': 'ACHETÉ', 'shopHelp': '1 pièce / 5 min · fleur 10 · routes et clôtures 5',
    'shopObjects': 'DÉCO',
    'catFlowers': 'FLEURS', 'catOuter': 'DÉCO EXT.', 'catInner': 'DÉCO INT.', 'catPets': 'ANIMAUX', 'comingSoon': 'BIENTÔT',
    'road_concrete': 'BÉTON', 'road_wood': 'CHEMIN BOIS', 'road_dirt': 'CHEMIN TERRE', 'road_stone': 'CHEMIN PIERRE',
    'fence_wood': 'CLÔTURE BOIS', 'fence_dark': 'CLÔTURE FONCÉE', 'fence_stone': 'CLÔTURE PIERRE',
    'garden': 'JARDIN', 'gardenHelp': 'PERSONNALISE, puis touche. Pince · glisse · pivote.',
    'customize': 'PERSONNALISER', 'done': 'OK', 'upgrade': 'AGRANDIR ({0})', 'maxSize': 'TAILLE MAX',
    'gardenSize': '{0} × {1}', 'upgraded': 'JARDIN AGRANDI', 'pickFlower': 'QUOI PLACER ?',
    'clearTile': 'VIDER LA CASE', 'needFlowers': "Achète d'abord dans la BOUTIQUE.",
    'noneLeft': 'Plus rien de ça à placer.', 'recenter': 'RECENTRER',
    'peek': 'MASQUER UI', 'camera': 'CAMÉRA', 'capture': 'CAPTURER', 'share': 'ENREGISTRER / PARTAGER',
    'setBackdrop': 'METTRE EN FOND', 'clearBackdrop': 'RETIRER LE FOND', 'cancel': 'ANNULER',
    'setLiveWallpaper': "FOND D'ÉCRAN ANIMÉ", 'wallpaperSet': "FOND D'ÉCRAN DÉFINI",
    'wallpaperFailed': "Impossible d'ouvrir le sélecteur de fond d'écran.",
    'homeMode': "ÉCRAN D'ACCUEIL", 'clean': 'SIMPLE', 'gardenMode': 'JARDIN',
    'appBlocker': "BLOCAGE D'APPS", 'blockedApps': 'APPS BLOQUÉES',
    'blockerPermTitle': 'AUTORISATIONS REQUISES',
    'blockerPermBody': "Pixel Pomo a besoin de l'Accessibilité (voir quelle appli est ouverte) et de l'affichage par-dessus (montrer l'écran focus).",
    'grantAccess': 'ACTIVER ACCESSIBILITÉ', 'grantOverlay': 'ACTIVER SUPERPOSITION',
    'stayFocused': 'RESTE CONCENTRÉ', 'backToPomo': 'RETOUR À PIXEL POMO',
    'pickBlocked': 'TOUCHE LES APPS À BLOQUER',
    'habits': 'HABITUDES', 'money': 'SUIVI ARGENT', 'mood': 'CETTE JOURNÉE ?',
    'addHabit': 'AJOUTER UNE HABITUDE', 'habitName': 'NOM', 'daysTimes': '{0} JOURS · {1} FOIS',
    'daysTimesTotal': '{0} JOURS · {1} FOIS · {2}',
    'style': 'STYLE', 'styleHorizontal': 'HORIZONTAL', 'styleVertical': 'VERTICAL',
    'streakN': 'SÉRIE DE {0} JOURS', 'noHabits': 'Ajoute une habitude ou lance une session.',
    'labelHabit': 'ÉTIQUETTE FOCUS', 'removeHabitMsg': 'Supprimer l\'habitude « {0} » ?',
    'income': 'REVENU', 'expense': 'DÉPENSE', 'addExpense': '+ DÉPENSE', 'addIncome': '+ REVENU',
    'amount': 'MONTANT', 'category': 'CATÉGORIE', 'note': 'NOTE (OPTION)', 'currency': 'DEVISE',
    'moneySettings': 'RÉGLAGES ARGENT', 'mainCurrency': 'DEVISE PRINCIPALE', 'dailyRate': 'BUDGET QUOTIDIEN',
    'dailyRateHelp': 'Dépense moins par jour → +1 pièce. 0 = off.', 'noTx': 'Aucune entrée ce mois-ci.',
    'spentToday': 'DÉPENSÉ AUJOURD\'HUI', 'ratesUpdated': 'TAUX MIS À JOUR', 'offline': 'HORS LIGNE · CACHE',
    'catFood': 'NOURRITURE', 'catTransport': 'TRANSPORT', 'catHome': 'MAISON', 'catFun': 'LOISIRS',
    'catHealth': 'SANTÉ', 'catShopping': 'SHOPPING', 'catEducation': 'ÉDUCATION', 'catOther': 'AUTRE',
    'catSalary': 'SALAIRE', 'catGift': 'CADEAU',
    'net': 'NET', 'addCategory': 'AJOUTER CATÉGORIE', 'categoryNameHint': 'NOM DE CATÉGORIE',
    'removeCategoryMsg': 'Supprimer la catégorie "{0}" ?', 'noRates': 'Taux non chargés — montants non convertis.',
    'noMoneyData': 'Aucune entrée sur cette période.', 'noSessionsPeriod': 'Aucune session de focus ici pour le moment.',
    'weekdayShort': 'LU,MA,ME,JE,VE,SA,DI',
    'yearInPixels': 'TON ANNÉE EN PIXELS (TOUT)', 'moodTracker': 'SUIVI HUMEUR', 'goals': 'TES OBJECTIFS', 'focusSessions': 'SESSIONS DE FOCUS',
    'sessionsTimelineWeek': 'CHRONOLOGIE HEBDO DES SESSIONS', 'sessionHeatmap': 'HEATMAP DES SESSIONS',
    'sessionsInPixels': 'SESSIONS EN PIXELS',
  },
  'it': {
    'work': 'FOCUS', 'break': 'PAUSA', 'start': 'AVVIA', 'pause': 'PAUSA', 'reset': 'AZZERA',
    'autoBreak': 'AVVIO AUTO', 'startBreakTitle': 'Iniziare la pausa?', 'startSessionTitle': 'Iniziare la prossima sessione?',
    'logHistory': 'CRONOLOGIA', 'changeLabel': 'CAMBIA ETICHETTA', 'noLogs': 'Nessuna sessione', 'pageOf': 'PAGINA {0}/{1}',
    'switchMode': '>> CAMBIA MODO', 'session': 'SESSIONE {0} / {1}', 'allDone': 'FATTO!',
    'workDone': 'FOCUS FINITO!', 'breakDone': 'PAUSA FINITA!',
    'settings': 'IMPOSTAZIONI', 'theme': 'TEMA', 'save': 'SALVA', 'close': 'CHIUDI',
    'timerMode': 'MODALITÀ TIMER', 'stopwatch': 'CRONOMETRO', 'pomodoro': 'POMODORO',
    'study': 'LAVORO (MIN)', 'breakMin': 'PAUSA (MIN)', 'sessions': 'SESSIONI',
    'settingsSaved': 'SALVATE', 'language': 'LINGUA',
    'label': 'ETICHETTA', 'newLabel': 'NUOVA ETICHETTA', 'add': 'AGGIUNGI', 'pickColor': 'SCEGLI COLORE',
    'renameTitle': 'RINOMINA ETICHETTA', 'renameHint': 'Tieni premuto per rinominare.',
    'removeTitle': 'Eliminare l\'etichetta?', 'removeMsg': 'Eliminare l\'etichetta "{0}"?', 'yes': 'SÌ', 'no': 'NO',
    'stats': 'STATISTICHE', 'today': 'OGGI', 'week': 'QUESTA SETTIMANA', 'month': 'QUESTO MESE',
    'year': 'QUEST\'ANNO', 'all': 'SEMPRE', 'byLabelMonth': 'PER ETICHETTA · {0}',
    'chartBar': 'BARRE', 'chartLine': 'TREND', 'chartPie': 'TORTA', 'chartNoData': 'Nessun minuto questo mese.',
    'statCurrent': 'ATTUALE', 'statAverage': 'MEDIA', 'statBest': 'MIGLIORE',
    'pDaily': 'GIORNO', 'pWeekly': 'SETTIMANA', 'pMonthly': 'MESE', 'pYearly': 'ANNO', 'pAll': 'TUTTO', 'byLabel': 'PER ETICHETTA',
    'p18Weeks': '18 SETTIMANE',
    'shop': 'NEGOZIO', 'buy': 'COMPRA', 'owned': 'POSSEDUTI {0}', 'notEnough': 'MONETE INSUFFICIENTI',
    'purchased': 'ACQUISTATO', 'shopHelp': '1 moneta / 5 min · fiore 10 · strada e recinto 5',
    'shopObjects': 'DECORO',
    'catFlowers': 'FIORI', 'catOuter': 'DECORO EST.', 'catInner': 'DECORO INT.', 'catPets': 'ANIMALI', 'comingSoon': 'IN ARRIVO',
    'road_concrete': 'CEMENTO', 'road_wood': 'VIA LEGNO', 'road_dirt': 'VIA TERRA', 'road_stone': 'VIA PIETRA',
    'fence_wood': 'REC. LEGNO', 'fence_dark': 'REC. SCURO', 'fence_stone': 'REC. PIETRA',
    'garden': 'GIARDINO', 'gardenHelp': 'PERSONALIZZA, poi tocca. Pizzica · trascina · ruota.',
    'customize': 'PERSONALIZZA', 'done': 'FATTO', 'upgrade': 'AMPLIA ({0})', 'maxSize': 'DIM. MAX',
    'gardenSize': '{0} × {1}', 'upgraded': 'GIARDINO AMPLIATO', 'pickFlower': 'COSA METTERE?',
    'clearTile': 'SVUOTA CELLA', 'needFlowers': 'Compra prima qualcosa nel NEGOZIO.',
    'noneLeft': 'Non hai più quello.', 'recenter': 'CENTRA',
    'peek': 'NASCONDI UI', 'camera': 'FOTOCAMERA', 'capture': 'SCATTA', 'share': 'SALVA / CONDIVIDI',
    'setBackdrop': 'IMPOSTA SFONDO', 'clearBackdrop': 'RIMUOVI SFONDO', 'cancel': 'ANNULLA',
    'setLiveWallpaper': 'IMPOSTA SFONDO LIVE', 'wallpaperSet': 'SFONDO IMPOSTATO',
    'wallpaperFailed': 'Impossibile aprire il selettore sfondi.',
    'homeMode': 'SCHERMATA', 'clean': 'PULITO', 'gardenMode': 'GIARDINO',
    'appBlocker': 'BLOCCO APP', 'blockedApps': 'APP BLOCCATE',
    'blockerPermTitle': 'PERMESSI NECESSARI',
    'blockerPermBody': 'Pixel Pomo richiede Accessibilità (vedere quale app è aperta) e Sovrapposizione (mostrare la schermata focus).',
    'grantAccess': 'ATTIVA ACCESSIBILITÀ', 'grantOverlay': 'ATTIVA SOVRAPPOSIZIONE',
    'stayFocused': 'RESTA CONCENTRATO', 'backToPomo': 'TORNA A PIXEL POMO',
    'pickBlocked': 'TOCCA LE APP DA BLOCCARE',
    'habits': 'ABITUDINI', 'money': 'MONITOR SPESE', 'mood': "COM'È ANDATA OGGI?",
    'addHabit': 'AGGIUNGI ABITUDINE', 'habitName': 'NOME', 'daysTimes': '{0} GIORNI · {1} VOLTE',
    'daysTimesTotal': '{0} GIORNI · {1} VOLTE · {2}',
    'style': 'STILE', 'styleHorizontal': 'ORIZZONTALE', 'styleVertical': 'VERTICALE',
    'streakN': 'SERIE DI {0} GIORNI', 'noHabits': "Aggiungi un'abitudine o avvia una sessione.",
    'labelHabit': 'ETICHETTA FOCUS', 'removeHabitMsg': 'Rimuovere l\'abitudine "{0}"?',
    'income': 'ENTRATA', 'expense': 'SPESA', 'addExpense': '+ SPESA', 'addIncome': '+ ENTRATA',
    'amount': 'IMPORTO', 'category': 'CATEGORIA', 'note': 'NOTA (OPZIONALE)', 'currency': 'VALUTA',
    'moneySettings': 'IMPOSTAZIONI DENARO', 'mainCurrency': 'VALUTA PRINCIPALE', 'dailyRate': 'BUDGET GIORNALIERO',
    'dailyRateHelp': 'Spendi meno al giorno → +1 moneta. 0 = off.', 'noTx': 'Nessuna voce questo mese.',
    'spentToday': 'SPESO OGGI', 'ratesUpdated': 'TASSI AGGIORNATI', 'offline': 'OFFLINE · CACHE',
    'catFood': 'CIBO', 'catTransport': 'TRASPORTI', 'catHome': 'CASA', 'catFun': 'SVAGO',
    'catHealth': 'SALUTE', 'catShopping': 'SHOPPING', 'catEducation': 'ISTRUZIONE', 'catOther': 'ALTRO',
    'catSalary': 'STIPENDIO', 'catGift': 'REGALO',
    'net': 'NETTO', 'addCategory': 'AGGIUNGI CATEGORIA', 'categoryNameHint': 'NOME CATEGORIA',
    'removeCategoryMsg': 'Rimuovere la categoria "{0}"?', 'noRates': 'Tassi non caricati — importi non convertiti.',
    'noMoneyData': 'Nessuna voce in questo periodo.', 'noSessionsPeriod': 'Ancora nessuna sessione di focus qui.',
    'weekdayShort': 'LU,MA,ME,GI,VE,SA,DO',
    'yearInPixels': 'IL TUO ANNO IN PIXEL (TUTTI I DATI)', 'moodTracker': 'MONITOR UMORE', 'goals': 'I TUOI OBIETTIVI', 'focusSessions': 'SESSIONI DI FOCUS',
    'sessionsTimelineWeek': 'CRONOLOGIA SESSIONI SETTIMANA', 'sessionHeatmap': 'HEATMAP SESSIONI',
    'sessionsInPixels': 'SESSIONI IN PIXEL',
  },
};

const Map<String, List<String>> _months = {
  'en': ['JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE', 'JULY', 'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER'],
  'tr': ['OCAK', 'ŞUBAT', 'MART', 'NİSAN', 'MAYIS', 'HAZİRAN', 'TEMMUZ', 'AĞUSTOS', 'EYLÜL', 'EKİM', 'KASIM', 'ARALIK'],
  'pl': ['STYCZEŃ', 'LUTY', 'MARZEC', 'KWIECIEŃ', 'MAJ', 'CZERWIEC', 'LIPIEC', 'SIERPIEŃ', 'WRZESIEŃ', 'PAŹDZIERNIK', 'LISTOPAD', 'GRUDZIEŃ'],
  'de': ['JANUAR', 'FEBRUAR', 'MÄRZ', 'APRIL', 'MAI', 'JUNI', 'JULI', 'AUGUST', 'SEPTEMBER', 'OKTOBER', 'NOVEMBER', 'DEZEMBER'],
  'fr': ['JANVIER', 'FÉVRIER', 'MARS', 'AVRIL', 'MAI', 'JUIN', 'JUILLET', 'AOÛT', 'SEPTEMBRE', 'OCTOBRE', 'NOVEMBRE', 'DÉCEMBRE'],
  'it': ['GENNAIO', 'FEBBRAIO', 'MARZO', 'APRILE', 'MAGGIO', 'GIUGNO', 'LUGLIO', 'AGOSTO', 'SETTEMBRE', 'OTTOBRE', 'NOVEMBRE', 'DICEMBRE'],
};

/// Language tag → display autonym (never translated), in settings order.
const List<List<String>> languageOptions = [
  ['en', 'English'],
  ['tr', 'Türkçe'],
  ['pl', 'Polski'],
  ['de', 'Deutsch'],
  ['fr', 'Français'],
  ['it', 'Italiano'],
];

String t(String lang, String key) => _s[lang]?[key] ?? _s['en']![key] ?? key;

String tf(String lang, String key, List<Object> args) {
  var s = t(lang, key);
  for (var i = 0; i < args.length; i++) {
    s = s.replaceAll('{$i}', args[i].toString());
  }
  return s;
}

String monthName(String lang, int month1) =>
    (_months[lang] ?? _months['en']!)[month1 - 1];
