// UI strings for the six supported languages (en/tr/pl/de/ko/it). A direct port of the
// Android `values[-xx]/strings.xml` sets. Lookup falls back to English for any missing key.

const Map<String, Map<String, String>> _s = {
  'en': {
    'work': 'WORK', 'break': 'BREAK', 'start': 'START', 'pause': 'PAUSE', 'reset': 'RESET',
    'switchMode': '>> SWITCH MODE', 'session': 'SESSION {0} / {1}', 'allDone': 'ALL DONE!',
    'workDone': 'WORK DONE!', 'breakDone': 'BREAK OVER!',
    'settings': 'SETTINGS', 'theme': 'THEME', 'save': 'SAVE', 'close': 'CLOSE',
    'study': 'STUDY (MIN)', 'breakMin': 'BREAK (MIN)', 'sessions': 'SESSIONS',
    'settingsSaved': 'SETTINGS SAVED', 'language': 'LANGUAGE',
    'label': 'LABEL', 'newLabel': 'NEW LABEL', 'add': 'ADD', 'pickColor': 'PICK A COLOR',
    'removeTitle': 'Remove label?', 'removeMsg': 'Remove the label "{0}"?', 'yes': 'YES', 'no': 'NO',
    'stats': 'STATS', 'today': 'TODAY', 'week': 'THIS WEEK', 'month': 'THIS MONTH',
    'year': 'THIS YEAR', 'all': 'ALL TIME', 'byLabelMonth': 'BY LABEL · {0}',
    'chartBar': 'BAR', 'chartLine': 'LINE', 'chartPie': 'PIE', 'chartNoData': 'No focus minutes this month.',
    'pDaily': 'DAILY', 'pWeekly': 'WEEKLY', 'pMonthly': 'MONTHLY', 'pYearly': 'YEARLY', 'pAll': 'ALL', 'byLabel': 'BY LABEL',
    'shop': 'SHOP', 'buy': 'BUY', 'owned': 'OWNED {0}', 'notEnough': 'NOT ENOUGH COINS',
    'purchased': 'PURCHASED', 'shopHelp': '1 coin / 5 focus min · flowers 10 · roads & fences 5',
    'shopObjects': 'DECOR',
    'road_concrete': 'CONCRETE', 'road_wood': 'WOOD PATH', 'road_dirt': 'DIRT PATH', 'road_stone': 'STONE PATH',
    'fence_wood': 'WOOD FENCE', 'fence_dark': 'DARK FENCE', 'fence_stone': 'STONE FENCE',
    'garden': 'GARDEN', 'gardenHelp': 'CUSTOMIZE, then tap tiles. Pinch zoom · drag pan · twist to rotate.',
    'customize': 'CUSTOMIZE', 'done': 'DONE', 'upgrade': 'EXPAND ({0})', 'maxSize': 'MAX SIZE',
    'gardenSize': '{0} × {1}', 'upgraded': 'GARDEN EXPANDED', 'pickFlower': 'PLACE WHAT?',
    'clearTile': 'CLEAR TILE', 'needFlowers': 'Buy something in the SHOP first.',
    'noneLeft': 'None of that left to place.', 'recenter': 'RECENTER',
    'peek': 'HIDE UI', 'camera': 'CAMERA', 'capture': 'CAPTURE', 'share': 'SAVE / SHARE',
    'setBackdrop': 'SET AS BACKDROP', 'clearBackdrop': 'CLEAR BACKDROP', 'cancel': 'CANCEL',
    'homeMode': 'HOME SCREEN', 'clean': 'CLEAN', 'gardenMode': 'GARDEN',
  },
  'tr': {
    'work': 'ÇALIŞ', 'break': 'MOLA', 'start': 'BAŞLAT', 'pause': 'DURAKLAT', 'reset': 'SIFIRLA',
    'switchMode': '>> MOD DEĞİŞTİR', 'session': 'SEANS {0} / {1}', 'allDone': 'BİTTİ!',
    'workDone': 'ÇALIŞMA BİTTİ!', 'breakDone': 'MOLA BİTTİ!',
    'settings': 'AYARLAR', 'theme': 'TEMA', 'save': 'KAYDET', 'close': 'KAPAT',
    'study': 'ÇALIŞMA (DK)', 'breakMin': 'MOLA (DK)', 'sessions': 'SEANS',
    'settingsSaved': 'AYARLAR KAYDEDİLDİ', 'language': 'DİL',
    'label': 'ETİKET', 'newLabel': 'YENİ ETİKET', 'add': 'EKLE', 'pickColor': 'RENK SEÇ',
    'removeTitle': 'Etiket silinsin mi?', 'removeMsg': '"{0}" etiketi silinsin mi?', 'yes': 'EVET', 'no': 'HAYIR',
    'stats': 'İSTATİSTİK', 'today': 'BUGÜN', 'week': 'BU HAFTA', 'month': 'BU AY',
    'year': 'BU YIL', 'all': 'TÜM ZAMANLAR', 'byLabelMonth': 'ETİKETE GÖRE · {0}',
    'chartBar': 'ÇUBUK', 'chartLine': 'ÇİZGİ', 'chartPie': 'PASTA', 'chartNoData': 'Bu ay odak dakikası yok.',
    'pDaily': 'GÜNLÜK', 'pWeekly': 'HAFTALIK', 'pMonthly': 'AYLIK', 'pYearly': 'YILLIK', 'pAll': 'TÜMÜ', 'byLabel': 'ETİKETE GÖRE',
    'shop': 'MAĞAZA', 'buy': 'AL', 'owned': 'SAHİP {0}', 'notEnough': 'YETERLİ ALTIN YOK',
    'purchased': 'SATIN ALINDI', 'shopHelp': '5 odak dk = 1 altın · çiçek 10 · yol ve çit 5',
    'shopObjects': 'SÜS',
    'road_concrete': 'BETON', 'road_wood': 'TAHTA YOL', 'road_dirt': 'TOPRAK YOL', 'road_stone': 'TAŞ YOL',
    'fence_wood': 'TAHTA ÇİT', 'fence_dark': 'KOYU ÇİT', 'fence_stone': 'TAŞ ÇİT',
    'garden': 'BAHÇE', 'gardenHelp': 'ÖZELLEŞTİR, sonra dokun. Yakınlaştır · sürükle · çevir.',
    'customize': 'ÖZELLEŞTİR', 'done': 'TAMAM', 'upgrade': 'BÜYÜT ({0})', 'maxSize': 'MAKS BOYUT',
    'gardenSize': '{0} × {1}', 'upgraded': 'BAHÇE BÜYÜTÜLDÜ', 'pickFlower': 'NE KOYALIM?',
    'clearTile': 'KAREYİ TEMİZLE', 'needFlowers': 'Önce MAĞAZA\'dan bir şey al.',
    'noneLeft': 'Koyacak o şeyden kalmadı.', 'recenter': 'ORTALA',
    'peek': 'GİZLE', 'camera': 'KAMERA', 'capture': 'ÇEK', 'share': 'KAYDET / PAYLAŞ',
    'setBackdrop': 'ARKA PLAN YAP', 'clearBackdrop': 'ARKA PLANI SİL', 'cancel': 'İPTAL',
    'homeMode': 'ANA EKRAN', 'clean': 'SADE', 'gardenMode': 'BAHÇE',
  },
  'pl': {
    'work': 'PRACA', 'break': 'PRZERWA', 'start': 'START', 'pause': 'PAUZA', 'reset': 'RESET',
    'switchMode': '>> ZMIEŃ TRYB', 'session': 'SESJA {0} / {1}', 'allDone': 'GOTOWE!',
    'workDone': 'KONIEC PRACY!', 'breakDone': 'KONIEC PRZERWY!',
    'settings': 'USTAWIENIA', 'theme': 'MOTYW', 'save': 'ZAPISZ', 'close': 'ZAMKNIJ',
    'study': 'PRACA (MIN)', 'breakMin': 'PRZERWA (MIN)', 'sessions': 'SESJE',
    'settingsSaved': 'ZAPISANO', 'language': 'JĘZYK',
    'label': 'ETYKIETA', 'newLabel': 'NOWA ETYKIETA', 'add': 'DODAJ', 'pickColor': 'WYBIERZ KOLOR',
    'removeTitle': 'Usunąć etykietę?', 'removeMsg': 'Usunąć etykietę "{0}"?', 'yes': 'TAK', 'no': 'NIE',
    'stats': 'STATYSTYKI', 'today': 'DZIŚ', 'week': 'TEN TYDZIEŃ', 'month': 'TEN MIESIĄC',
    'year': 'TEN ROK', 'all': 'CAŁY CZAS', 'byLabelMonth': 'WG ETYKIETY · {0}',
    'chartBar': 'SŁUPKI', 'chartLine': 'LINIA', 'chartPie': 'KOŁO', 'chartNoData': 'Brak minut w tym miesiącu.',
    'pDaily': 'DZIENNE', 'pWeekly': 'TYGODNIE', 'pMonthly': 'MIESIĄC', 'pYearly': 'ROCZNE', 'pAll': 'WSZYSTKO', 'byLabel': 'WG ETYKIETY',
    'shop': 'SKLEP', 'buy': 'KUP', 'owned': 'MASZ {0}', 'notEnough': 'ZA MAŁO MONET',
    'purchased': 'KUPIONO', 'shopHelp': '1 moneta / 5 min · kwiat 10 · droga i płot 5',
    'shopObjects': 'DEKORACJE',
    'road_concrete': 'BETON', 'road_wood': 'DROGA DREW.', 'road_dirt': 'DROGA ZIEM.', 'road_stone': 'DROGA KAM.',
    'fence_wood': 'PŁOT DREW.', 'fence_dark': 'CIEMNY PŁOT', 'fence_stone': 'PŁOT KAM.',
    'garden': 'OGRÓD', 'gardenHelp': 'DOSTOSUJ, potem dotykaj. Szczyp · przeciągnij · obróć.',
    'customize': 'DOSTOSUJ', 'done': 'GOTOWE', 'upgrade': 'ROZBUDUJ ({0})', 'maxSize': 'MAKS. ROZMIAR',
    'gardenSize': '{0} × {1}', 'upgraded': 'OGRÓD ROZBUDOWANY', 'pickFlower': 'CO POSTAWIĆ?',
    'clearTile': 'WYCZYŚĆ POLE', 'needFlowers': 'Najpierw kup coś w SKLEPIE.',
    'noneLeft': 'Nie masz już tego.', 'recenter': 'WYŚRODKUJ',
    'peek': 'UKRYJ UI', 'camera': 'APARAT', 'capture': 'ZRÓB', 'share': 'ZAPISZ / UDOSTĘPNIJ',
    'setBackdrop': 'USTAW TŁO', 'clearBackdrop': 'USUŃ TŁO', 'cancel': 'ANULUJ',
    'homeMode': 'EKRAN GŁÓWNY', 'clean': 'CZYSTY', 'gardenMode': 'OGRÓD',
  },
  'de': {
    'work': 'ARBEIT', 'break': 'PAUSE', 'start': 'START', 'pause': 'PAUSE', 'reset': 'ZURÜCK',
    'switchMode': '>> MODUS WECHSELN', 'session': 'RUNDE {0} / {1}', 'allDone': 'FERTIG!',
    'workDone': 'ARBEIT FERTIG!', 'breakDone': 'PAUSE VORBEI!',
    'settings': 'EINSTELLUNGEN', 'theme': 'THEMA', 'save': 'SPEICHERN', 'close': 'SCHLIESSEN',
    'study': 'ARBEIT (MIN)', 'breakMin': 'PAUSE (MIN)', 'sessions': 'RUNDEN',
    'settingsSaved': 'GESPEICHERT', 'language': 'SPRACHE',
    'label': 'LABEL', 'newLabel': 'NEUES LABEL', 'add': 'HINZU', 'pickColor': 'FARBE WÄHLEN',
    'removeTitle': 'Label löschen?', 'removeMsg': 'Label "{0}" löschen?', 'yes': 'JA', 'no': 'NEIN',
    'stats': 'STATISTIK', 'today': 'HEUTE', 'week': 'DIESE WOCHE', 'month': 'DIESER MONAT',
    'year': 'DIESES JAHR', 'all': 'GESAMT', 'byLabelMonth': 'NACH LABEL · {0}',
    'chartBar': 'BALKEN', 'chartLine': 'LINIE', 'chartPie': 'KREIS', 'chartNoData': 'Keine Minuten in diesem Monat.',
    'pDaily': 'TÄGLICH', 'pWeekly': 'WÖCHENTL', 'pMonthly': 'MONATL', 'pYearly': 'JÄHRL', 'pAll': 'GESAMT', 'byLabel': 'NACH LABEL',
    'shop': 'SHOP', 'buy': 'KAUFEN', 'owned': 'BESITZ {0}', 'notEnough': 'ZU WENIG MÜNZEN',
    'purchased': 'GEKAUFT', 'shopHelp': '1 Münze / 5 Min · Blume 10 · Straße & Zaun 5',
    'shopObjects': 'DEKO',
    'road_concrete': 'BETON', 'road_wood': 'HOLZWEG', 'road_dirt': 'ERDWEG', 'road_stone': 'STEINWEG',
    'fence_wood': 'HOLZZAUN', 'fence_dark': 'DUNKLER ZAUN', 'fence_stone': 'STEINZAUN',
    'garden': 'GARTEN', 'gardenHelp': 'ANPASSEN, dann tippen. Zoomen · ziehen · drehen.',
    'customize': 'ANPASSEN', 'done': 'FERTIG', 'upgrade': 'ERWEITERN ({0})', 'maxSize': 'MAX. GRÖSSE',
    'gardenSize': '{0} × {1}', 'upgraded': 'GARTEN ERWEITERT', 'pickFlower': 'WAS SETZEN?',
    'clearTile': 'FELD LEEREN', 'needFlowers': 'Kaufe zuerst etwas im SHOP.',
    'noneLeft': 'Nichts davon mehr übrig.', 'recenter': 'ZENTRIEREN',
    'peek': 'UI AUS', 'camera': 'KAMERA', 'capture': 'AUFNAHME', 'share': 'SPEICHERN / TEILEN',
    'setBackdrop': 'ALS HINTERGRUND', 'clearBackdrop': 'HINTERGRUND LÖSCHEN', 'cancel': 'ABBRECHEN',
    'homeMode': 'STARTBILDSCHIRM', 'clean': 'SCHLICHT', 'gardenMode': 'GARTEN',
  },
  'ko': {
    'work': '집중', 'break': '휴식', 'start': '시작', 'pause': '일시정지', 'reset': '초기화',
    'switchMode': '>> 모드 전환', 'session': '세션 {0} / {1}', 'allDone': '완료!',
    'workDone': '집중 완료!', 'breakDone': '휴식 끝!',
    'settings': '설정', 'theme': '테마', 'save': '저장', 'close': '닫기',
    'study': '집중 (분)', 'breakMin': '휴식 (분)', 'sessions': '세션',
    'settingsSaved': '설정 저장됨', 'language': '언어',
    'label': '라벨', 'newLabel': '새 라벨', 'add': '추가', 'pickColor': '색상 선택',
    'removeTitle': '라벨을 삭제할까요?', 'removeMsg': '"{0}" 라벨을 삭제할까요?', 'yes': '예', 'no': '아니오',
    'stats': '통계', 'today': '오늘', 'week': '이번 주', 'month': '이번 달',
    'year': '올해', 'all': '전체', 'byLabelMonth': '라벨별 · {0}',
    'chartBar': '막대', 'chartLine': '선', 'chartPie': '원형', 'chartNoData': '이번 달 기록이 없습니다.',
    'pDaily': '일간', 'pWeekly': '주간', 'pMonthly': '월간', 'pYearly': '연간', 'pAll': '전체', 'byLabel': '라벨별',
    'shop': '상점', 'buy': '구매', 'owned': '보유 {0}', 'notEnough': '코인이 부족합니다',
    'purchased': '구매 완료', 'shopHelp': '5분당 1코인 · 꽃 10 · 길과 울타리 5',
    'shopObjects': '장식',
    'road_concrete': '콘크리트', 'road_wood': '나무길', 'road_dirt': '흙길', 'road_stone': '돌길',
    'fence_wood': '나무 울타리', 'fence_dark': '진한 울타리', 'fence_stone': '돌 울타리',
    'garden': '정원', 'gardenHelp': '꾸미기 후 타일 탭. 확대 · 이동 · 회전.',
    'customize': '꾸미기', 'done': '완료', 'upgrade': '확장 ({0})', 'maxSize': '최대 크기',
    'gardenSize': '{0} × {1}', 'upgraded': '정원 확장됨', 'pickFlower': '무엇을 놓을까요?',
    'clearTile': '타일 비우기', 'needFlowers': '먼저 상점에서 구매하세요.',
    'noneLeft': '놓을 것이 없습니다.', 'recenter': '가운데로',
    'peek': 'UI 숨기기', 'camera': '카메라', 'capture': '촬영', 'share': '저장 / 공유',
    'setBackdrop': '배경으로', 'clearBackdrop': '배경 지우기', 'cancel': '취소',
    'homeMode': '홈 화면', 'clean': '심플', 'gardenMode': '정원',
  },
  'it': {
    'work': 'LAVORO', 'break': 'PAUSA', 'start': 'AVVIA', 'pause': 'PAUSA', 'reset': 'AZZERA',
    'switchMode': '>> CAMBIA MODO', 'session': 'SESSIONE {0} / {1}', 'allDone': 'FATTO!',
    'workDone': 'LAVORO FINITO!', 'breakDone': 'PAUSA FINITA!',
    'settings': 'IMPOSTAZIONI', 'theme': 'TEMA', 'save': 'SALVA', 'close': 'CHIUDI',
    'study': 'LAVORO (MIN)', 'breakMin': 'PAUSA (MIN)', 'sessions': 'SESSIONI',
    'settingsSaved': 'SALVATE', 'language': 'LINGUA',
    'label': 'ETICHETTA', 'newLabel': 'NUOVA ETICHETTA', 'add': 'AGGIUNGI', 'pickColor': 'SCEGLI COLORE',
    'removeTitle': 'Eliminare l\'etichetta?', 'removeMsg': 'Eliminare l\'etichetta "{0}"?', 'yes': 'SÌ', 'no': 'NO',
    'stats': 'STATISTICHE', 'today': 'OGGI', 'week': 'QUESTA SETTIMANA', 'month': 'QUESTO MESE',
    'year': 'QUEST\'ANNO', 'all': 'SEMPRE', 'byLabelMonth': 'PER ETICHETTA · {0}',
    'chartBar': 'BARRE', 'chartLine': 'LINEA', 'chartPie': 'TORTA', 'chartNoData': 'Nessun minuto questo mese.',
    'pDaily': 'GIORNO', 'pWeekly': 'SETTIMANA', 'pMonthly': 'MESE', 'pYearly': 'ANNO', 'pAll': 'TUTTO', 'byLabel': 'PER ETICHETTA',
    'shop': 'NEGOZIO', 'buy': 'COMPRA', 'owned': 'POSSEDUTI {0}', 'notEnough': 'MONETE INSUFFICIENTI',
    'purchased': 'ACQUISTATO', 'shopHelp': '1 moneta / 5 min · fiore 10 · strada e recinto 5',
    'shopObjects': 'DECORO',
    'road_concrete': 'CEMENTO', 'road_wood': 'VIA LEGNO', 'road_dirt': 'VIA TERRA', 'road_stone': 'VIA PIETRA',
    'fence_wood': 'REC. LEGNO', 'fence_dark': 'REC. SCURO', 'fence_stone': 'REC. PIETRA',
    'garden': 'GIARDINO', 'gardenHelp': 'PERSONALIZZA, poi tocca. Pizzica · trascina · ruota.',
    'customize': 'PERSONALIZZA', 'done': 'FATTO', 'upgrade': 'AMPLIA ({0})', 'maxSize': 'DIM. MAX',
    'gardenSize': '{0} × {1}', 'upgraded': 'GIARDINO AMPLIATO', 'pickFlower': 'COSA METTERE?',
    'clearTile': 'SVUOTA CELLA', 'needFlowers': 'Compra prima qualcosa nel NEGOZIO.',
    'noneLeft': 'Non hai più quello.', 'recenter': 'CENTRA',
    'peek': 'NASCONDI UI', 'camera': 'FOTOCAMERA', 'capture': 'SCATTA', 'share': 'SALVA / CONDIVIDI',
    'setBackdrop': 'IMPOSTA SFONDO', 'clearBackdrop': 'RIMUOVI SFONDO', 'cancel': 'ANNULLA',
    'homeMode': 'SCHERMATA', 'clean': 'PULITO', 'gardenMode': 'GIARDINO',
  },
};

const Map<String, List<String>> _months = {
  'en': ['JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE', 'JULY', 'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER'],
  'tr': ['OCAK', 'ŞUBAT', 'MART', 'NİSAN', 'MAYIS', 'HAZİRAN', 'TEMMUZ', 'AĞUSTOS', 'EYLÜL', 'EKİM', 'KASIM', 'ARALIK'],
  'pl': ['STYCZEŃ', 'LUTY', 'MARZEC', 'KWIECIEŃ', 'MAJ', 'CZERWIEC', 'LIPIEC', 'SIERPIEŃ', 'WRZESIEŃ', 'PAŹDZIERNIK', 'LISTOPAD', 'GRUDZIEŃ'],
  'de': ['JANUAR', 'FEBRUAR', 'MÄRZ', 'APRIL', 'MAI', 'JUNI', 'JULI', 'AUGUST', 'SEPTEMBER', 'OKTOBER', 'NOVEMBER', 'DEZEMBER'],
  'ko': ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
  'it': ['GENNAIO', 'FEBBRAIO', 'MARZO', 'APRILE', 'MAGGIO', 'GIUGNO', 'LUGLIO', 'AGOSTO', 'SETTEMBRE', 'OTTOBRE', 'NOVEMBRE', 'DICEMBRE'],
};

/// Language tag → display autonym (never translated), in settings order.
const List<List<String>> languageOptions = [
  ['en', 'English'],
  ['tr', 'Türkçe'],
  ['pl', 'Polski'],
  ['de', 'Deutsch'],
  ['ko', '한국어'],
  ['it', 'Italiano'],
];

String t(String lang, String key) => _s[lang]?[key] ?? _s['en']![key] ?? key;

String tf(String lang, String key, List<Object> args) {
  var s = t(lang, key);
  for (var i = 0; i < args.length; i++) {
    s = s.replaceAll('{$i}', args[i].toString());
  }
  return s;
}

String monthName(String lang, int month1) =>
    (_months[lang] ?? _months['en']!)[month1 - 1];
